/* Atelier Français. JavaScript nativo: funciona em file:// e em subpastas do GitHub Pages. */
'use strict';
const $ = (q,root=document)=>root.querySelector(q);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const lessons=window.LESSONS, guide=window.GUIDE;
const words=lessons.flatMap(l=>l.words.map(w=>({...w,lesson:l.id,title:l.title})));
const sourceMap={
 salutations:{title:'TV5MONDE · Primeiros cumprimentos',url:'https://apprendre.tv5monde.com/fr/exercices/premiere-classe/les-salutations',desc:'Recurso complementar com escuta e atividades de apresentação.'},
 liaison:{title:'TV5MONDE · La liaison',url:'https://apprendre.tv5monde.com/fr/aides/prononciation-la-liaison',desc:'Referência complementar para a ligação entre palavras.'},
 phonetics:{title:'Usito · Transcrição fonética',url:'https://usito.usherbrooke.ca/articles/m%C3%A9tadonn%C3%A9es/phonetiquePrincipes',desc:'Dicionário da Université de Sherbrooke: notação fonética, h mudo e h aspirado. A descrição inclui particularidades do francês quebequense.'},
 articles:{title:'TV5MONDE · Artigos definidos e indefinidos',url:'https://apprendre.tv5monde.com/fr/aides/grammaire-le-presentatif-les-articles-definis-et-indefinis-0',desc:'Apoio para reconhecer un, une, des, le, la e les.'},
 present:{title:'Lingolia · O presente',url:'https://francais.lingolia.com/fr/grammaire/les-temps/le-present',desc:'Referência para formas e usos do presente; exercícios adicionais no site de origem.'},
 places:{title:'TV5MONDE · Cidades e países',url:'https://apprendre.tv5monde.com/fr/aides/grammaire-les-prepositions-au-en-aux-nom-de-ville-ou-de-pays',desc:'Complemento sobre à, au, en e aux com cidades e países.'},
 past:{title:'TV5MONDE · Passé composé',url:'https://apprendre.tv5monde.com/fr/aides/grammaire-le-passe-compose',desc:'Formação básica: auxiliar no presente e particípio passado.'},
 holidays:{title:'Service Public · Contexto dos feriados',url:'https://www.service-public.fr/particuliers/actualites/A15406?lang=fr',desc:'Página de calendário de 2025 consultada para contextualizar diferenças territoriais. Não é o calendário do ano corrente.'}
};
const ranges=[['Pronúncia',1,1],['Primeiros contatos e perguntas',2,7],['Tempo e posição',8,10],['Números e quantidades',10,13],['Clima, calendário e horas',13,21],['Expressões, opostos e cores',21,26],['Transportes e direções',26,29],['Mecânica',29,31],['Serviços e dinheiro',31,33],['Correio e telefone',33,36],['Urgências',36,38],['Alimentos e condimentos',38,47],['Compras e objetos',47,52],['Vestuário',52,55],['Saúde e farmácia',55,59],['Entretenimento',59,60],['Restaurante',61,64],['Hotel e formulários',64,69],['Página final',70,70]];
let state={done:[],last:'primeiras-palavras'},storageOK=true;
try{const s=JSON.parse(localStorage.getItem('atelier-francais-v1')||'null');if(s&&Array.isArray(s.done)){state.done=s.done.filter(id=>lessons.some(l=>l.id===id));if(lessons.some(l=>l.id===s.last))state.last=s.last;}}catch{storageOK=false;}
function save(){try{localStorage.setItem('atelier-francais-v1',JSON.stringify(state));}catch{storageOK=false;toast('Seu progresso ficará apenas nesta sessão: armazenamento indisponível.');}}
let toastTimer;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4500);}
function sound(text){return `<button class="sound" data-speak="${esc(text)}" aria-label="Ouvir: ${esc(text)}" title="Ouvir em francês">▶</button>`;}
let speakingButton=null;
function speak(text,button){
 if(!('speechSynthesis' in window)){toast('Este navegador não oferece leitura em voz alta. Use as fontes de escuta na página Fontes.');return;}
 speechSynthesis.cancel();if(speakingButton)speakingButton.classList.remove('playing');
 const voices=speechSynthesis.getVoices();const voice=voices.find(v=>v.lang.toLowerCase()==='fr-fr')||voices.find(v=>v.lang.toLowerCase().startsWith('fr'));
 if(!voice){toast('Nenhuma voz francesa está disponível. Instale uma voz em francês nas configurações do dispositivo.');return;}
 const utterance=new SpeechSynthesisUtterance(text);utterance.lang=voice.lang;utterance.voice=voice;utterance.rate=.85;
 speakingButton=button;button?.classList.add('playing');
 utterance.onend=()=>button?.classList.remove('playing');utterance.onerror=()=>{button?.classList.remove('playing');toast('O áudio não pôde ser reproduzido. Verifique as vozes do dispositivo.');};speechSynthesis.speak(utterance);
}
if('speechSynthesis' in window){speechSynthesis.getVoices();speechSynthesis.addEventListener('voiceschanged',()=>speechSynthesis.getVoices());}
function card(l){const i=lessons.indexOf(l)+1;return `<a class="course-card" href="#aula/${l.id}"><div class="card-top"><span class="chapter-num">${String(i).padStart(2,'0')}</span>${state.done.includes(l.id)?'<span class="check">✓ Concluída</span>':`<span class="tag">${esc(l.group)}</span>`}</div><h3>${esc(l.title)}</h3><p>${esc(l.subtitle)}</p><div class="card-meta"><span>${l.words.length} expressões · ${l.quiz.length} exercícios</span><span aria-hidden="true">↗</span></div></a>`;}
function home(){
 const current=lessons.find(l=>l.id===state.last)||lessons[0];const pct=Math.round(state.done.length/lessons.length*100);
 return `<section class="intro"><div><div class="eyebrow">BIENVENUE À L’ATELIER</div><h1>Um pouco, <em>todos os dias.</em></h1><p>Seu próximo passo no francês começa com uma conversa.</p></div><div class="intro-side"><strong>${String(state.done.length).padStart(2,'0')}<span style="font-size:1rem;color:var(--muted)"> / 22</span></strong>aulas concluídas</div></section>
 <div class="hero-grid"><section class="lesson-feature"><div class="feature-top"><span class="tag light-tag">${state.done.length?'CONTINUE SUA JORNADA':'SEU PRIMEIRO PASSO'}</span><span>AULA ${String(lessons.indexOf(current)+1).padStart(2,'0')}</span></div><h2>${esc(current.title)}</h2><p>${esc(current.subtitle)}<br>Leia, escute e coloque em prática.</p><div class="feature-bottom"><a class="btn lime" href="#aula/${current.id}">${state.done.length?'Continuar aprendendo':'Começar a aula'} <span aria-hidden="true">→</span></a><span class="mini-note">No seu ritmo. Sem pressa.</span></div></section>
 <section class="daily"><div class="daily-head">UMA EXPRESSÃO PARA HOJE <span aria-hidden="true">✧</span></div><div class="word" lang="fr">Enchanté.</div><p>Muito prazer.<br>Uma pequena palavra para<br>uma nova conexão.</p><div class="play-word">${sound('Enchanté.')}<small>Ouça e repita<br>Voz do seu dispositivo</small></div></section></div>
 <div class="stats"><div class="stat"><strong>22</strong><span>aulas explicadas</span></div><div class="stat"><strong>156</strong><span>expressões revisadas</span></div><div class="stat"><strong>44</strong><span>exercícios</span></div><div class="stat"><strong>70</strong><span>páginas do guia</span></div></div>
 <div class="section-top"><h2>Construa sua base</h2><a class="text-link" href="#aulas">Ver todas as aulas ↗</a></div><div class="cards">${lessons.slice(0,3).map(card).join('')}</div>
 <div class="mini-banner"><span class="monogram" aria-hidden="true">01—70</span><div><h3>Seu guia completo, sempre por perto.</h3><p>Consulte todas as páginas do PDF e as observações de revisão.</p></div><a href="#guia/1" class="text-link">Abrir o guia ↗</a></div>
 ${state.done.length?`<div class="section-top"><h2>Seu progresso</h2><span class="muted">${pct}%</span></div><div class="progress-track" role="progressbar" aria-label="Aulas concluídas" aria-valuenow="${state.done.length}" aria-valuemin="0" aria-valuemax="22"><span style="width:${pct}%"></span></div>`:''}<p class="storage-note">${storageOK?'Seu progresso é salvo somente neste navegador.':'Armazenamento indisponível: o progresso é mantido somente nesta sessão.'}</p>`;
}
function allLessons(){return `<div class="page-heading"><div class="eyebrow">LE PARCOURS</div><h1>Um caminho para conversar.</h1><p>Comece pelos fundamentos e avance para situações do dia a dia. Todas as aulas estão abertas.</p></div><div class="filter-bar" aria-label="Filtrar aulas">${['Todas','Comece aqui','Fundamentos','Na vida real','Próximo passo'].map((g,i)=>`<button class="chip ${i?'':'selected'}" data-group="${g}" aria-pressed="${!i}">${g}</button>`).join('')}</div><div class="cards" id="course-list">${lessons.map(card).join('')}</div>`;}
function phrases(list){return `<div class="phrase-list">${list.map(w=>`<div class="phrase-row"><div><strong lang="fr">${esc(w.fr)}</strong><div class="translation">${esc(w.pt)}</div>${w.title?`<a class="topic" href="#aula/${w.lesson}">${esc(w.title)} ↗</a>`:''}</div>${sound(w.fr)}</div>`).join('')}</div>`;}
function quizMarkup(q,i,prefix='lesson'){return `<section class="quiz-card" data-question="${i}"><span class="quiz-number">QUESTÃO ${i+1}</span><h3>${esc(q.prompt)}</h3><div class="answers">${q.options.map((o,j)=>`<button class="answer" data-answer="${j}" data-quiz="${prefix}" data-question-index="${i}"><span class="letter">${String.fromCharCode(65+j)}</span><span>${esc(o)}</span></button>`).join('')}</div><div class="feedback" aria-live="polite"></div></section>`;}
let activeLesson=null;
function lesson(id){
 const l=lessons.find(l=>l.id===id);if(!l)return notFound();activeLesson=l;state.last=l.id;save();const index=lessons.indexOf(l),done=state.done.includes(l.id);
 return `<a class="back-link" href="#aulas">← Todas as aulas</a><div class="lesson-layout"><article class="lesson-content"><div class="eyebrow">AULA ${String(index+1).padStart(2,'0')} / 22 · ${esc(l.group)}</div><h1 class="lesson-title">${esc(l.title)}</h1><p class="lesson-subtitle">${esc(l.subtitle)}</p>${l.sections.map((s,i)=>`<section class="lesson-section" id="sec-${i}"><h2>${esc(s.title)}</h2><p>${esc(s.text)}</p></section>`).join('')}
 <aside class="note"><strong>Leve para a prática</strong>${esc(l.tip)}</aside><section class="lesson-section" id="expressoes"><h2>Escute. Repita. Use.</h2>${phrases(l.words)}<p class="audio-hint">Áudio sintetizado com uma voz francesa disponível no dispositivo. A pronúncia pode variar conforme a voz; complemente com falantes reais nas fontes.</p></section>
 <section class="lesson-section" id="exercicios"><h2>Sua vez de tentar</h2><p>Escolha uma resposta e entenda o porquê.</p>${l.quiz.map((q,i)=>quizMarkup(q,i)).join('')}</section>
 <div class="source-inline">${l.pages.length?`<a href="#guia/${l.pages[0]}">Guia original · p. ${l.pages.join('–')}</a>`:'<span class="muted">Aula complementar ao guia.</span>'}${l.sources.map(k=>`<a href="${sourceMap[k].url}" target="_blank" rel="noopener noreferrer">${esc(sourceMap[k].title)} ↗</a>`).join('')}</div>
 <div class="lesson-bottom"><button class="btn ${done?'secondary':''}" data-complete="${l.id}">${done?'✓ Aula concluída':'Marcar como concluída'}</button>${index<lessons.length-1?`<a class="btn secondary" href="#aula/${lessons[index+1].id}">Próxima aula →</a>`:'<a class="btn secondary" href="#pratica">Revisar o que aprendi →</a>'}</div></article>
 <aside class="lesson-aside"><h3>Nesta aula</h3><span class="muted">${l.words.length} expressões · ${l.quiz.length} exercícios</span><div class="aside-toc">${l.sections.map((s,i)=>`<a href="#sec-${i}" data-scroll="sec-${i}">${esc(s.title)}</a>`).join('')}<a href="#expressoes" data-scroll="expressoes">Expressões com áudio</a><a href="#exercicios" data-scroll="exercicios">Exercícios</a></div><hr><strong id="aside-progress">${state.done.length} de 22 aulas concluídas</strong><div class="progress-track"><span id="aside-progress-fill" style="width:${state.done.length/22*100}%"></span></div><small class="muted">No seu ritmo, neste navegador.</small></aside></div>`;
}
function vocabulary(){return `<div class="page-heading"><div class="eyebrow">LES MOTS DU QUOTIDIEN</div><h1>Palavras que viram conversa.</h1><p>156 expressões das aulas, com tradução em português e leitura em voz alta. O vocabulário integral do PDF está no <a class="text-link" href="#guia/1">guia completo</a>.</p></div><div class="search"><label class="sr-only" for="word-search">Buscar em francês ou português</label><input id="word-search" type="search" placeholder="Buscar em francês ou português…" autocomplete="off"><label class="sr-only" for="word-topic">Filtrar por aula</label><select id="word-topic"><option value="">Todos os temas</option>${lessons.map(l=>`<option value="${l.id}">${esc(l.title)}</option>`).join('')}</select></div><p class="audio-hint">As vozes francesas dependem do navegador e das configurações do dispositivo.</p><div id="word-results">${wordResults(words)}</div>`;}
function wordResults(list){return `<p class="count-label">${list.length} ${list.length===1?'expressão encontrada':'expressões encontradas'}</p>${list.length?phrases(list):'<div class="empty">Nenhuma expressão encontrada. Tente outra palavra ou consulte a busca do guia completo.</div>'}`;}
function updateWords(){const query=norm($('#word-search').value),topic=$('#word-topic').value;$('#word-results').innerHTML=wordResults(words.filter(w=>(!topic||w.lesson===topic)&&norm(w.fr+' '+w.pt).includes(query)));}
function guidePage(n){const page=Math.max(1,Math.min(70,parseInt(n)||1)),topic=ranges.find(r=>page>=r[1]&&page<=r[2]);return `<div class="page-heading"><div class="eyebrow">LA BIBLIOTHÈQUE</div><h1>O guia, por inteiro.</h1><p>Todas as 70 páginas do material enviado. A transcrição preserva a escrita original, inclusive termos antigos e incorreções. Para aprender, priorize as aulas revisadas e consulte as <a href="#fontes" class="text-link">correções</a>.</p></div><a class="btn secondary" href="assets/guia-original.pdf" target="_blank" rel="noopener">Abrir PDF original ↗</a> <a class="btn secondary" href="assets/guia-original.pdf" download="Guia-completo-frances.pdf">Baixar PDF ↓</a>
 <details><summary>Índice dos assuntos</summary><div class="toc-grid">${ranges.map(r=>`<a href="#guia/${r[1]}">${esc(r[0])}<span>p. ${r[1]}${r[2]!==r[1]?'–'+r[2]:''}</span></a>`).join('')}</div></details>
 <div class="search"><label for="guide-search" class="sr-only">Buscar nas 70 páginas</label><input id="guide-search" type="search" placeholder="Buscar em todas as páginas do guia…" autocomplete="off"></div><div id="guide-search-results"></div>
 <div id="guide-reader"><div class="page-control"><a class="btn secondary small" ${page>1?`href="#guia/${page-1}"`:'aria-disabled="true"'}>← Anterior</a><label for="page-select">Página</label><select id="page-select">${guide.map(p=>`<option value="${p.page}" ${p.page===page?'selected':''}>${p.page} de 70</option>`).join('')}</select><a class="btn secondary small" ${page<70?`href="#guia/${page+1}"`:'aria-disabled="true"'}>Próxima →</a></div><section class="original-box"><span class="tag">DOCUMENTO ORIGINAL · PÁGINA ${page}</span><h2 style="margin:15px 0">${esc(topic?.[0]||'Continuação do guia')}</h2><p class="original-notice">Transcrição de consulta, sem revisão editorial. Em telas pequenas, deslize a tabela horizontalmente. O PDF mantém a diagramação original.</p>${page===70?'<p class="muted">A última página contém apenas o número 70.</p>':''}<div class="original-scroll" tabindex="0" role="region" aria-label="Transcrição da página ${page}, com rolagem horizontal"><pre>${esc(guide[page-1].text)}</pre></div></section></div>`;}
function searchGuide(){const raw=$('#guide-search').value.trim(),q=norm(raw);$('#guide-reader').hidden=!!q;if(!q){$('#guide-search-results').innerHTML='';return;}const matches=guide.filter(p=>norm(p.text).includes(q));$('#guide-search-results').innerHTML=`<p class="count-label">${matches.length} ${matches.length===1?'página':'páginas'} com “${esc(raw)}”</p>`+(matches.length?matches.map(p=>{let idx=norm(p.text).indexOf(q);return `<a class="guide-result" href="#guia/${p.page}"><strong>Página ${p.page} ↗</strong><p>…${esc(p.text.slice(Math.max(0,idx-80),idx+180).replace(/\s+/g,' '))}…</p></a>`;}).join(''):'<div class="empty">Nenhuma página encontrada. Tente a palavra em francês ou um sinônimo.</div>');}
const corrections=[
 ['1','s entre vogais → k','Em maison, s soa /z/. Ss normalmente representa /s/.'],['1','au → “ou”; ll → “lh”','Au geralmente é /o/. Em fille/feuille aparece /j/; em ville/mille, /l/.'],['1','Todas as finais se ligam à vogal seguinte','A liaison depende do contexto. Não ocorre depois de et nem antes de h aspirado.'],['1','am/an/em/en/um/un como um só som','Distinguir /ɑ̃/, /ɛ̃/, /ɔ̃/ e, em variedades que o mantêm, /œ̃/.'],['2','l’arrête de autobus; office du ourisme','L’arrêt de bus; l’office du tourisme.'],['3','Comment appele-t-on…','Comment appelle-t-on…'],['17','8 de maio: Fête de la Libération','Victoire de 1945 é a referência adequada. A lista não é um calendário completo e uniforme.'],['25','Meuilleur','Meilleur.'],['33, 50','Escudos e francos franceses','Contexto monetário antigo. Use euros nos exemplos atuais da França; o franco suíço é uma moeda distinta.'],['36','Je n’écoute pas = não consigo ouvir','Je ne vous entends pas. Écouter é escutar; entendre é ouvir.'],['36','l’assault','A grafia é assaut; para agressão ou roubo, escolha agression ou vol conforme o contexto.'],['39–41','Le côte; le dinde; la lièvre','La côte; la dinde; le lièvre.'],['40','Chevreuil = cabrito-montês','Chevreuil = corço.'],['46, 64','La poivre; romarin = rosmaninho','Le poivre; romarin = alecrim.'],['53','Les pantalon','Le pantalon / les pantalons.'],['56–57','Constipação / enrhumé','No português brasileiro: resfriado. Constipation em francês é prisão de ventre.'],['57, 59','Aux toucher; eau oxigénée; pas une ordonnance','Au toucher; eau oxygénée; je n’ai pas d’ordonnance, para ausência de receita.'],['60','Metteur en scène para todo diretor','No cinema, réalisateur/réalisatrice; no teatro, metteur/metteuse en scène.'],['63','La cuillière; huile = azeite','La cuillère (ou cuiller); huile é óleo, huile d’olive especifica azeite.'],['69','Apelido / nome','No formulário: nom = sobrenome; prénom = primeiro nome.']
];
function sources(){return `<div class="page-heading"><div class="eyebrow">LES RÉFÉRENCES</div><h1>Aprender com contexto.</h1><p>O guia é o ponto de partida. As aulas reorganizam os assuntos, explicam estruturas e corrigem problemas identificados no original.</p></div><section class="source-card"><h3>Material principal · Guia completo francês_.pdf</h3><p>70 páginas fornecidas por você: pronúncia, expressões, números, tempo, transportes, serviços, urgências, alimentos, compras, roupas, saúde, lazer, restaurante e hotel. Todo o original está disponível na consulta por página e no PDF incluído.</p><a href="#guia/1">Consultar o material completo ↗</a></section><section class="note"><strong>Como usar este material</strong>O percurso é introdutório, orientado a situações de comunicação; não promete um nível certificado. As explicações e exercícios foram redigidos para este site. O PDF original não passou por revisão integral. Sua transcrição é preservada como referência, sem validar cada tradução ou aproximação de pronúncia. Há diferenças entre o francês da França, de outros países e entre registros de fala.</section><h2>Fontes para aprofundar</h2><p class="muted">Consulta realizada em 22 de setembro de 2026. Links externos podem mudar. As referências abaixo apoiam temas específicos e não representam uma validação de todo o guia.</p>${Object.values(sourceMap).map(s=>`<article class="source-card"><h3>${esc(s.title)}</h3><p>${esc(s.desc)}</p><a href="${s.url}" target="_blank" rel="noopener noreferrer">Visitar a fonte ↗</a></article>`).join('')}<h2 style="margin-top:35px">Correções e observações do guia</h2><p class="muted">Lista de problemas identificados durante a preparação. As aulas usam formas revisadas; a consulta original mantém o documento como enviado.</p><div class="table-scroll"><table class="corrections"><thead><tr><th>Página</th><th>No original</th><th>Como estudar</th></tr></thead><tbody>${corrections.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><section class="note"><strong>Sobre o áudio</strong>Os botões usam síntese de voz do navegador, sem gravações próprias. A disponibilidade, o sotaque e a necessidade de conexão variam conforme as vozes instaladas. Não há avaliação automática da sua pronúncia.</section>`;}
let session=null;
function practice(){session=null;return `<div class="page-heading"><div class="eyebrow">À VOUS DE JOUER</div><h1>Transforme leitura em memória.</h1><p>Tente lembrar antes de olhar a resposta. Depois, volte à explicação e use a frase em voz alta.</p></div><div class="practice-setup"><section class="practice-box"><span class="tag">REVISÃO GUIADA</span><h2>Teste o que aprendeu.</h2><p>Questões com correção imediata e explicações. Escolha uma aula ou misture os assuntos.</p><label class="sr-only" for="quiz-topic">Tema do exercício</label><select id="quiz-topic"><option value="">Revisão geral · 10 questões</option>${lessons.map(l=>`<option value="${l.id}">${esc(l.title)}</option>`).join('')}</select><button class="btn" data-start="quiz">Começar exercícios →</button></section><section class="practice-box"><span class="tag">CARTÕES DE MEMÓRIA</span><h2>Uma expressão de cada vez.</h2><p>Leia em francês, tente traduzir e revele a resposta. Ouça a expressão e repita.</p><label class="sr-only" for="flash-topic">Tema dos cartões</label><select id="flash-topic"><option value="">Todos os temas · 12 cartões</option>${lessons.map(l=>`<option value="${l.id}">${esc(l.title)}</option>`).join('')}</select><button class="btn secondary" data-start="flash">Revisar expressões →</button></section></div><div class="note"><strong>Um jeito simples de estudar</strong>Leia uma aula, repita as expressões e faça os exercícios. No dia seguinte, tente lembrar as mesmas frases antes de reler. Combine o estudo com escuta de pessoas reais e conversas curtas.</div>`;}
function shuffled(a){const b=[...a];for(let i=b.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;}
function startPractice(type){const topic=$(`#${type==='quiz'?'quiz':'flash'}-topic`).value;const pool=type==='quiz'?lessons.filter(l=>!topic||l.id===topic).flatMap(l=>l.quiz):words.filter(w=>!topic||w.lesson===topic);session={type,items:shuffled(pool).slice(0,topic?pool.length:(type==='quiz'?10:12)),index:0,score:0,answered:false,revealed:false};renderSession();}
function renderSession(){if(!session)return;const s=session,finished=s.index>=s.items.length;if(finished){$('#main').innerHTML=`<div class="practice-stage"><div class="eyebrow">REVISÃO CONCLUÍDA</div><h1>${s.type==='quiz'?'Cada tentativa ensina.':'Mais palavras com você.'}</h1><div class="score">${s.type==='quiz'?s.score:s.items.length}<span style="font-size:1.6rem;color:var(--muted)"> / ${s.items.length}</span></div><p class="muted">${s.type==='quiz'?'Respostas corretas nesta rodada. Volte às aulas para revisar os pontos que ainda precisam de prática.':'Cartões revisados. Agora tente usar três dessas expressões numa conversa imaginária.'}</p><a href="#pratica" class="btn" data-restart>Praticar novamente</a> <a href="#aulas" class="btn secondary">Voltar às aulas</a></div>`;return;}
 const item=s.items[s.index];$('#main').innerHTML=`<div class="practice-stage"><a class="back-link" href="#pratica" data-restart>← Escolher outra prática</a><div class="practice-status"><span>${s.type==='quiz'?'Exercício':'Cartão'} ${s.index+1} de ${s.items.length}</span><span>${s.type==='quiz'?s.score+' acertos':'Leia, lembre, repita'}</span></div><div class="progress-track"><span style="width:${s.index/s.items.length*100}%"></span></div>${s.type==='quiz'?`${quizMarkup(item,s.index,'session')}<button class="btn" data-next disabled>Próxima questão →</button>`:`<section class="flashcard"><div class="eyebrow">COMO VOCÊ DIRIA EM PORTUGUÊS?</div><div class="french" lang="fr">${esc(item.fr)}</div>${sound(item.fr)}<div id="flash-translation" class="translation" aria-live="polite"></div></section><div class="practice-actions"><button class="btn" data-reveal>Revelar tradução</button><button class="btn secondary" data-next disabled>Próximo cartão →</button></div>`}</div>`;}
function answer(button){const index=Number(button.dataset.questionIndex),choice=Number(button.dataset.answer),inSession=button.dataset.quiz==='session';const q=inSession?session?.items[index]:activeLesson?.quiz[index];if(!q)return;const card=button.closest('.quiz-card');if(card.dataset.answered)return;card.dataset.answered='true';const good=choice===q.answer;card.querySelectorAll('.answer').forEach((b,j)=>{b.disabled=true;if(j===q.answer)b.classList.add('correct');else if(j===choice)b.classList.add('wrong');});$('.feedback',card).innerHTML=`<strong>${good?'✓ Resposta correta.':'Ainda não. A resposta correta está destacada.'}</strong> ${esc(q.explanation)}`;if(inSession){session.answered=true;if(good)session.score++;$('[data-next]').disabled=false;}}
function notFound(){return '<div class="empty"><h1>Página não encontrada.</h1><p>Escolha uma aula para continuar.</p><a class="btn" href="#aulas">Ver aulas</a></div>';}
function render(){
 const [page='inicio',id]=(location.hash.slice(1)||'inicio').split('/');activeLesson=null;session=null;if('speechSynthesis' in window)speechSynthesis.cancel();
 const views={inicio:home,aulas:allLessons,aula:()=>lesson(id),vocabulario:vocabulary,guia:()=>guidePage(id),fontes:sources,pratica:practice};$('#main').innerHTML=(views[page]||notFound)();
 const labels={inicio:'Sua jornada de aprendizado',aulas:'Seu percurso de estudo',aula:'Aprender · '+(activeLesson?.title||'Aula'),vocabulario:'Seu vocabulário',guia:'Material de referência',fontes:'Fontes e revisão',pratica:'Prática e revisão'};$('#breadcrumb').textContent=labels[page]||'Atelier Français';document.title=(activeLesson?.title||labels[page]||'Início')+' — Atelier Français';
 document.querySelectorAll('[data-nav]').forEach(a=>{const active=a.dataset.nav===(page==='aula'?'aulas':page);a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('#sidebar').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');window.scrollTo(0,0);$('#main').focus({preventScroll:true});
}
document.addEventListener('click',e=>{
 if(e.target.closest('.skip')){e.preventDefault();$('#main').focus();return;}
 const speech=e.target.closest('[data-speak]');if(speech){speak(speech.dataset.speak,speech);return;}
 const menu=e.target.closest('.menu-toggle');if(menu){const open=$('#sidebar').classList.toggle('open');menu.setAttribute('aria-expanded',String(open));if(open)$('#sidebar a').focus();return;}
 if($('#sidebar').classList.contains('open')&&!e.target.closest('#sidebar')){$('#sidebar').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');}
 const scroll=e.target.closest('[data-scroll]');if(scroll){e.preventDefault();document.getElementById(scroll.dataset.scroll)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});return;}
 const group=e.target.closest('[data-group]');if(group){document.querySelectorAll('[data-group]').forEach(b=>{b.classList.toggle('selected',b===group);b.setAttribute('aria-pressed',String(b===group));});$('#course-list').innerHTML=lessons.filter(l=>group.dataset.group==='Todas'||l.group===group.dataset.group).map(card).join('');return;}
 const complete=e.target.closest('[data-complete]');if(complete){const id=complete.dataset.complete;if(!state.done.includes(id)){state.done.push(id);save();complete.textContent='✓ Aula concluída';complete.classList.add('secondary');$('#aside-progress').textContent=state.done.length+' de 22 aulas concluídas';$('#aside-progress-fill').style.width=state.done.length/22*100+'%';toast(storageOK?'Aula concluída. Seu progresso foi salvo neste navegador.':'Aula concluída nesta sessão.');}return;}
 const answerButton=e.target.closest('[data-answer]');if(answerButton){answer(answerButton);return;}
 const start=e.target.closest('[data-start]');if(start){startPractice(start.dataset.start);return;}
 const reveal=e.target.closest('[data-reveal]');if(reveal&&session){$('#flash-translation').textContent=session.items[session.index].pt;session.revealed=true;reveal.disabled=true;$('[data-next]').disabled=false;return;}
 const next=e.target.closest('[data-next]');if(next&&session&&!next.disabled){session.index++;session.answered=false;session.revealed=false;renderSession();return;}
 const restart=e.target.closest('[data-restart]');if(restart){e.preventDefault();$('#main').innerHTML=practice();window.scrollTo(0,0);return;}
});
document.addEventListener('input',e=>{if(e.target.id==='word-search')updateWords();if(e.target.id==='guide-search')searchGuide();});
document.addEventListener('change',e=>{if(e.target.id==='word-topic')updateWords();if(e.target.id==='page-select')location.hash='guia/'+e.target.value;});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#sidebar').classList.contains('open')){$('#sidebar').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');$('.menu-toggle').focus();}});
window.addEventListener('hashchange',render);render();

// Amélioration progressive: l’interface reste indépendante de cette API expérimentale.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 try{Promise.resolve(document.modelContext.registerTool({
  name:'open_french_lesson',title:'Abrir uma aula de francês',
  description:'Navega para uma aula existente. Não marca a aula como concluída. Use o identificador da aula.',
  inputSchema:{type:'object',properties:{lessonId:{type:'string',enum:lessons.map(l=>l.id)}},required:['lessonId'],additionalProperties:false},
  annotations:{readOnlyHint:false,untrustedContentHint:false},
  execute(input){
   if(!input||typeof input.lessonId!=='string'||Object.keys(input).some(k=>k!=='lessonId'))throw new Error('Informe somente lessonId.');
   const selected=lessons.find(l=>l.id===input.lessonId);if(!selected)throw new Error('Aula inexistente.');
   history.replaceState(null,'','#aula/'+selected.id);render();return {lessonId:selected.id,title:selected.title,opened:true};
  }
 },{signal:lifecycle.signal})).catch(()=>{});}catch{}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
